- package:
    name: "{{ base_packages }}"
    state: present

- lineinfile:
    path: /etc/hosts
    line: "{{ item }}"
    state: present
  loop: "{{ hosts_entries }}"

- copy:
    dest: /etc/sudoers.d/99-vagrant
    content: "%vagrant ALL=(ALL) NOPASSWD:ALL\n"
    mode: "0440"

- user:
    name: vagrant
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- authorized_key:
    user: vagrant
    manage_dir: yes
    key: "{{ lookup('file', '/home/vagrant/.ssh/id_rsa.pub') }}"

- name: Crear archivo de datos del grupo
  ansible.builtin.shell: | 
        mkdir -p /tmp/Grupo
        version=$(lsb_release -d | cut -f2-)
        cpus=$(nproc)
        cat <<EOF > /tmp/Grupo/datos.txt
            Nombre Grupo: Di Loreto
            División: 313
            Fecha: 29/6
            -------------------------
            Distribución: $version
            Cantidad de Cores: $cpus
            -------------------------
            R1: Nombre: <Tu-Nombre> Apellido: <Tu-Apellido>
            R2: Nombre: <Tu-Nombre> Apellido: <Tu-Apellido>
            R3: Nombre: <Tu-Nombre> Apellido: <Tu-Apellido>
            R4: Nombre: <Tu-Nombre> Apellido: <Tu-Apellido>
            R5: Nombre: <Tu-Nombre> Apellido: <Tu-Apellido>
            R6: Nombre: <Tu-Nombre> Apellido: <Tu-Apellido>
            EOF