Vagrant.configure("2") do |config|
  RAM  = 1024
  CPUS = 1

  # Carpeta compartida por rsync (válido en WSL)
  config.vm.synced_folder ".", "/vagrant", type: "rsync", rsync__auto: true

  #  VM1 · Ubuntu 
  config.vm.define "VM1-Grupo-Diloreto" do |vm|
    vm.vm.box      = "ubuntu/jammy64"
    vm.vm.hostname = "vm1-grupo-diloreto"
    vm.vm.network  "private_network", ip: "192.168.56.11"

    vm.vm.provider "virtualbox" do |vb|
      vb.memory = RAM
      vb.cpus   = CPUS
      vb.gui    = true 
      vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"]

    end

    vm.vm.disk :disk, size: "5GB", name: "data5G"
    vm.vm.disk :disk, size: "3GB", name: "data3G"
    vm.vm.disk :disk, size: "2GB", name: "data2G"
    vm.vm.disk :disk, size: "1GB", name: "data1G"

    vm.vm.provision "ansible_local",
                    playbook: "/vagrant/ansible/deploy.yml",
                    install:  true
  end  

  #  VM2 · Fedora 
  config.vm.define "VM2-Grupo-Diloreto" do |vm|
    vm.vm.box      = "fedora/39-cloud-base"
    vm.vm.hostname = "vm2-grupo-diloreto"
    vm.vm.network  "private_network", ip: "192.168.56.12"

    vm.vm.provider "virtualbox" do |vb|
      vb.memory = RAM
      vb.cpus   = CPUS
      vb.gui    = true 
      vb.customize ["modifyvm", :id, "--uartmode1", "disconnected"] # para correrlo en WSL 

    end

    vm.vm.disk :disk, size: "5GB", name: "data5G"
    vm.vm.disk :disk, size: "3GB", name: "data3G"
    vm.vm.disk :disk, size: "2GB", name: "data2G"
    vm.vm.disk :disk, size: "1GB", name: "data1G"

    vm.vm.provision "ansible_local",
                    playbook: "/vagrant/ansible/deploy.yml",
                    install:  true
  end 
end    
