- name: TP – Aprovisionamiento mínimo
  hosts: all
  become: true
  roles:
    - common
    - lvm
    - web-server
    
- name: Arrancar contenedores NGINX
  hosts: all
  become: true
  vars:
    project_src_path: "/app"
  tasks:

    - name: Setear seguridad para Fedora
      ansible.builtin.shell: |
        sudo setenforce 0
      when: ansible_os_family == "RedHat"

    - name: Levantar servicios de Docker Compose
      community.docker.docker_compose_v2:
        project_src: "{{ project_src_path }}/nginx"
        files:
          - docker-compose.yml
        state: present

    - name: Verificar que docker compose funcione
      ansible.builtin.shell: docker compose version
      register: compose_check
      ignore_errors: true

    - name: Mostrar error si docker compose no está disponible
      debug:
        msg: "El plugin docker compose no está disponible correctamente en Fedora"
      when: compose_check.rc != 0